# Generated by Django 5.2.6 on 2025-09-22 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_bookcopy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField()),
                ('bookcopy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.bookcopy')),
            ],
        ),
    ]
