# Generated by Django 5.2.6 on 2025-09-22 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0005_library_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lib.student'),
        ),
    ]
