# Generated by Django 5.2.6 on 2025-09-22 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0006_borrowing_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarian',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lib.library'),
        ),
    ]
