# Generated by Django 5.2.6 on 2025-10-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0007_librarian_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=2),
        ),
    ]
