# Generated by Django 5.2.6 on 2025-10-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0008_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('NA', 'Not Availabe')], max_length=4),
        ),
    ]
