# Generated by Django 5.2.6 on 2025-10-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0009_alter_bookcopy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_status',
            field=models.CharField(choices=[('R', 'REGISTERED'), ('NA', 'NOT REGISTERED')], max_length=4),
        ),
    ]
