# Generated by Django 5.2.6 on 2025-10-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0010_alter_student_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=2),
        ),
    ]
