# Generated by Django 5.2.6 on 2025-10-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0011_alter_librarian_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('F', 'Fiction'), ('NF', 'Non Fiction'), ('S', 'Science'), ('E', 'Encyclopedia')], max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('O', 'ONE'), ('T', 'TWO'), ('TH', 'THREE'), ('F', 'FOUR')], max_length=4),
        ),
    ]
